var pieceType;
(function (pieceType) {
    pieceType[pieceType["pawn"] = 0] = "pawn";
    pieceType[pieceType["knight"] = 1] = "knight";
    pieceType[pieceType["bishop"] = 2] = "bishop";
    pieceType[pieceType["rook"] = 3] = "rook";
    pieceType[pieceType["queen"] = 4] = "queen";
    pieceType[pieceType["king"] = 5] = "king";
})(pieceType || (pieceType = {}));
var pieceColor;
(function (pieceColor) {
    pieceColor[pieceColor["white"] = 0] = "white";
    pieceColor[pieceColor["black"] = 1] = "black";
})(pieceColor || (pieceColor = {}));
var coordinate;
(function (coordinate) {
    coordinate[coordinate["a1"] = 0] = "a1";
    coordinate[coordinate["a2"] = 1] = "a2";
    coordinate[coordinate["a3"] = 2] = "a3";
    coordinate[coordinate["a4"] = 3] = "a4";
    coordinate[coordinate["a5"] = 4] = "a5";
    coordinate[coordinate["a6"] = 5] = "a6";
    coordinate[coordinate["a7"] = 6] = "a7";
    coordinate[coordinate["a8"] = 7] = "a8";
    coordinate[coordinate["b1"] = 8] = "b1";
    coordinate[coordinate["b2"] = 9] = "b2";
    coordinate[coordinate["b3"] = 10] = "b3";
    coordinate[coordinate["b4"] = 11] = "b4";
    coordinate[coordinate["b5"] = 12] = "b5";
    coordinate[coordinate["b6"] = 13] = "b6";
    coordinate[coordinate["b7"] = 14] = "b7";
    coordinate[coordinate["b8"] = 15] = "b8";
    coordinate[coordinate["c1"] = 16] = "c1";
    coordinate[coordinate["c2"] = 17] = "c2";
    coordinate[coordinate["c3"] = 18] = "c3";
    coordinate[coordinate["c4"] = 19] = "c4";
    coordinate[coordinate["c5"] = 20] = "c5";
    coordinate[coordinate["c6"] = 21] = "c6";
    coordinate[coordinate["c7"] = 22] = "c7";
    coordinate[coordinate["c8"] = 23] = "c8";
    coordinate[coordinate["d1"] = 24] = "d1";
    coordinate[coordinate["d2"] = 25] = "d2";
    coordinate[coordinate["d3"] = 26] = "d3";
    coordinate[coordinate["d4"] = 27] = "d4";
    coordinate[coordinate["d5"] = 28] = "d5";
    coordinate[coordinate["d6"] = 29] = "d6";
    coordinate[coordinate["d7"] = 30] = "d7";
    coordinate[coordinate["d8"] = 31] = "d8";
    coordinate[coordinate["e1"] = 32] = "e1";
    coordinate[coordinate["e2"] = 33] = "e2";
    coordinate[coordinate["e3"] = 34] = "e3";
    coordinate[coordinate["e4"] = 35] = "e4";
    coordinate[coordinate["e5"] = 36] = "e5";
    coordinate[coordinate["e6"] = 37] = "e6";
    coordinate[coordinate["e7"] = 38] = "e7";
    coordinate[coordinate["e8"] = 39] = "e8";
    coordinate[coordinate["f1"] = 40] = "f1";
    coordinate[coordinate["f2"] = 41] = "f2";
    coordinate[coordinate["f3"] = 42] = "f3";
    coordinate[coordinate["f4"] = 43] = "f4";
    coordinate[coordinate["f5"] = 44] = "f5";
    coordinate[coordinate["f6"] = 45] = "f6";
    coordinate[coordinate["f7"] = 46] = "f7";
    coordinate[coordinate["f8"] = 47] = "f8";
    coordinate[coordinate["g1"] = 48] = "g1";
    coordinate[coordinate["g2"] = 49] = "g2";
    coordinate[coordinate["g3"] = 50] = "g3";
    coordinate[coordinate["g4"] = 51] = "g4";
    coordinate[coordinate["g5"] = 52] = "g5";
    coordinate[coordinate["g6"] = 53] = "g6";
    coordinate[coordinate["g7"] = 54] = "g7";
    coordinate[coordinate["g8"] = 55] = "g8";
    coordinate[coordinate["h1"] = 56] = "h1";
    coordinate[coordinate["h2"] = 57] = "h2";
    coordinate[coordinate["h3"] = 58] = "h3";
    coordinate[coordinate["h4"] = 59] = "h4";
    coordinate[coordinate["h5"] = 60] = "h5";
    coordinate[coordinate["h6"] = 61] = "h6";
    coordinate[coordinate["h7"] = 62] = "h7";
    coordinate[coordinate["h8"] = 63] = "h8";
})(coordinate || (coordinate = {}));
class piece {
    constructor(iconpath, type, color, coordinate) {
        this.iconPath = iconpath;
        this.type = type;
        this.color = color;
        this.position = coordinate;
    }
}
